package dev.yaklede.bybittrader.api.backtest

import dev.yaklede.bybittrader.domain.ResearchCandleLimits
import dev.yaklede.bybittrader.domain.Symbol
import dev.yaklede.bybittrader.domain.Timeframe
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowBacktestConfig
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowBacktestReport
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowBacktestService
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowBacktestTrade
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowEntryMode
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowExitMode
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowMarketRegime
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowSetupMode
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowSideMode
import dev.yaklede.bybittrader.engine.backtest.VolumeFlowTagSummary
import dev.yaklede.bybittrader.engine.backtest.defaultVolumeFlowMarketRegimes
import io.ktor.server.auth.authenticate
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.routing.Route
import io.ktor.server.routing.post
import kotlinx.serialization.Serializable

fun Route.configureVolumeFlowBacktestRoutes(volumeFlowBacktestService: VolumeFlowBacktestService) {
    authenticate("control") {
        post("/backtests/volume-flow/run") {
            val request = call.receive<VolumeFlowBacktestRequest>().validated()
            val result =
                volumeFlowBacktestService.run(
                    symbol = Symbol(request.symbol),
                    m1Limit = request.m1Limit,
                    m5Limit = request.m5Limit,
                    m15Limit = request.m15Limit,
                    config = request.toConfig(),
                )
            call.respond(result.toResponse())
        }
    }
}

@Serializable
data class VolumeFlowBacktestRequest(
    val symbol: String,
    val m1Limit: Int = 3_000,
    val m5Limit: Int = 1_000,
    val m15Limit: Int = 500,
    val initialEquity: Double = 10_000.0,
    val riskFraction: Double = 0.0075,
    val feeRate: Double = 0.0006,
    val slippageRate: Double = 0.0002,
    val quantityStep: Double? = null,
    val minQuantity: Double? = null,
    val maxQuantity: Double? = null,
    val maxNotional: Double? = null,
    val leverage: Double? = null,
    val liquidationBufferPct: Double = 0.6,
    val setupMode: String = "BREAKOUT_CONTINUATION",
    val entryMode: String = "RETEST_CONFIRMATION",
    val sideMode: String = "BOTH",
    val setupTimeframe: String = "M5",
    val volumeLookback: Int = 20,
    val relativeVolumeThreshold: Double = 5.0,
    val maxRelativeVolumeThreshold: Double? = null,
    val relativeVolumeRiskThreshold: Double? = null,
    val relativeVolumeRiskMultiplier: Double = 1.0,
    val relativeVolumeRiskMaxTrendMovePct: Double? = null,
    val volumeZScoreThreshold: Double = 1.5,
    val setupRangeLookback: Int = 12,
    val requireM5Vwap: Boolean = false,
    val m5VwapLookback: Int = 12,
    val contextVwapLookback: Int = 32,
    val requireContextVwap: Boolean = true,
    val requireContextTrend: Boolean = true,
    val requireMacroTrendAlignment: Boolean = false,
    val macroTrendLookbackM15Candles: Int = 192,
    val minMacroTrendMovePct: Double = 0.0,
    val minMacroTrendEfficiency: Double? = null,
    val macroTrendEfficiencyRelativeVolumeMin: Double? = null,
    val macroTrendEfficiencyRelativeVolumeMax: Double? = null,
    val macroTrendMismatchRiskMultiplier: Double = 1.0,
    val allowedMarketRegimes: List<String>? = null,
    val requireRegimeSideAlignment: Boolean = false,
    val minTrendMovePct: Double = 0.003,
    val minTrendEfficiency: Double = 0.35,
    val highVolatilityRangePct: Double = 0.006,
    val contextRangeRiskThresholdPct: Double? = null,
    val contextRangeRiskMultiplier: Double = 1.0,
    val highContextRangeRelativeVolumeThresholdPct: Double? = null,
    val highContextRangeRelativeVolumeMin: Double? = null,
    val highContextRangeRelativeVolumeMacroBypassMovePct: Double? = null,
    val highContextRangeRelativeVolumeMacroBypassEfficiency: Double? = null,
    val maxContextRangePct: Double? = null,
    val minContextQuoteVolume: Double? = null,
    val requireKeyLevelProximity: Boolean = false,
    val keyLevelTolerancePct: Double = 0.0025,
    val avoidRangeMiddle: Boolean = false,
    val minBodyRatio: Double = 0.45,
    val minDirectionalCloseStrength: Double = 0.70,
    val minRejectionWickRatio: Double = 0.25,
    val entryLookaheadM1Candles: Int = 5,
    val entryRetestTolerancePct: Double = 0.0015,
    val minEntryBodyRatio: Double? = null,
    val minEntryRiskPct: Double? = null,
    val maxEntryRiskPct: Double? = null,
    val maxEntryRelativeVolume: Double? = null,
    val maxEstimatedFeeR: Double = 0.2,
    val targetR: Double = 1.2,
    val exitMode: String = "FIXED_TARGET",
    val runnerTrailActivationR: Double = 1.0,
    val runnerTrailDistanceR: Double = 0.5,
    val trendBreakLookbackM1Candles: Int = 5,
    val breakevenTriggerR: Double? = null,
    val followThroughCheckM1Candles: Int? = null,
    val minFollowThroughR: Double? = null,
    val followThroughMinContextRangePct: Double? = null,
    val adverseExitCheckM1Candles: Int? = null,
    val maxAdverseRBeforeExit: Double? = null,
    val minFavorableRBeforeAdverseExit: Double? = null,
    val profitProtectActivationR: Double? = null,
    val profitProtectFloorR: Double? = null,
    val maxHoldM1Candles: Int = 30,
    val dailyTargetPct: Double? = null,
    val dailyStopPct: Double = 1.0,
    val minTradesPerDay: Int = 1,
    val maxTradesPerDay: Int = 5,
    val maxConsecutiveLosses: Int = 3,
) {
    fun validated(): VolumeFlowBacktestRequest {
        Symbol(symbol)
        VolumeFlowSetupMode.valueOf(setupMode)
        VolumeFlowEntryMode.valueOf(entryMode)
        VolumeFlowExitMode.valueOf(exitMode)
        VolumeFlowSideMode.valueOf(sideMode)
        allowedMarketRegimes?.forEach(VolumeFlowMarketRegime::valueOf)
        val parsedSetupTimeframe = Timeframe.valueOf(setupTimeframe)
        require(parsedSetupTimeframe == Timeframe.M1 || parsedSetupTimeframe == Timeframe.M5) {
            "Setup timeframe must be M1 or M5."
        }
        require(m1Limit in 60..ResearchCandleLimits.MAX_M1_REPLAY_CANDLES) {
            "M1 limit must be between 60 and ${ResearchCandleLimits.MAX_M1_REPLAY_CANDLES}."
        }
        require(m5Limit in 30..ResearchCandleLimits.MAX_M5_REPLAY_CANDLES) {
            "M5 limit must be between 30 and ${ResearchCandleLimits.MAX_M5_REPLAY_CANDLES}."
        }
        require(m15Limit in 30..ResearchCandleLimits.MAX_M15_REPLAY_CANDLES) {
            "M15 limit must be between 30 and ${ResearchCandleLimits.MAX_M15_REPLAY_CANDLES}."
        }
        toConfig()
        return this
    }

    fun toConfig(): VolumeFlowBacktestConfig =
        VolumeFlowBacktestConfig(
            initialEquity = initialEquity,
            riskFraction = riskFraction,
            feeRate = feeRate,
            slippageRate = slippageRate,
            quantityStep = quantityStep,
            minQuantity = minQuantity,
            maxQuantity = maxQuantity,
            maxNotional = maxNotional,
            leverage = leverage,
            liquidationBufferPct = liquidationBufferPct,
            setupMode = VolumeFlowSetupMode.valueOf(setupMode),
            entryMode = VolumeFlowEntryMode.valueOf(entryMode),
            sideMode = VolumeFlowSideMode.valueOf(sideMode),
            setupTimeframe = Timeframe.valueOf(setupTimeframe),
            volumeLookback = volumeLookback,
            relativeVolumeThreshold = relativeVolumeThreshold,
            maxRelativeVolumeThreshold = maxRelativeVolumeThreshold,
            relativeVolumeRiskThreshold = relativeVolumeRiskThreshold,
            relativeVolumeRiskMultiplier = relativeVolumeRiskMultiplier,
            relativeVolumeRiskMaxTrendMovePct = relativeVolumeRiskMaxTrendMovePct,
            volumeZScoreThreshold = volumeZScoreThreshold,
            setupRangeLookback = setupRangeLookback,
            requireM5Vwap = requireM5Vwap,
            m5VwapLookback = m5VwapLookback,
            contextVwapLookback = contextVwapLookback,
            requireContextVwap = requireContextVwap,
            requireContextTrend = requireContextTrend,
            requireMacroTrendAlignment = requireMacroTrendAlignment,
            macroTrendLookbackM15Candles = macroTrendLookbackM15Candles,
            minMacroTrendMovePct = minMacroTrendMovePct,
            minMacroTrendEfficiency = minMacroTrendEfficiency,
            macroTrendEfficiencyRelativeVolumeMin = macroTrendEfficiencyRelativeVolumeMin,
            macroTrendEfficiencyRelativeVolumeMax = macroTrendEfficiencyRelativeVolumeMax,
            macroTrendMismatchRiskMultiplier = macroTrendMismatchRiskMultiplier,
            allowedMarketRegimes = allowedMarketRegimes?.map(VolumeFlowMarketRegime::valueOf)?.toSet() ?: defaultVolumeFlowMarketRegimes,
            requireRegimeSideAlignment = requireRegimeSideAlignment,
            minTrendMovePct = minTrendMovePct,
            minTrendEfficiency = minTrendEfficiency,
            highVolatilityRangePct = highVolatilityRangePct,
            contextRangeRiskThresholdPct = contextRangeRiskThresholdPct,
            contextRangeRiskMultiplier = contextRangeRiskMultiplier,
            highContextRangeRelativeVolumeThresholdPct = highContextRangeRelativeVolumeThresholdPct,
            highContextRangeRelativeVolumeMin = highContextRangeRelativeVolumeMin,
            highContextRangeRelativeVolumeMacroBypassMovePct = highContextRangeRelativeVolumeMacroBypassMovePct,
            highContextRangeRelativeVolumeMacroBypassEfficiency = highContextRangeRelativeVolumeMacroBypassEfficiency,
            maxContextRangePct = maxContextRangePct,
            minContextQuoteVolume = minContextQuoteVolume,
            requireKeyLevelProximity = requireKeyLevelProximity,
            keyLevelTolerancePct = keyLevelTolerancePct,
            avoidRangeMiddle = avoidRangeMiddle,
            minBodyRatio = minBodyRatio,
            minDirectionalCloseStrength = minDirectionalCloseStrength,
            minRejectionWickRatio = minRejectionWickRatio,
            entryLookaheadM1Candles = entryLookaheadM1Candles,
            entryRetestTolerancePct = entryRetestTolerancePct,
            minEntryBodyRatio = minEntryBodyRatio,
            minEntryRiskPct = minEntryRiskPct,
            maxEntryRiskPct = maxEntryRiskPct,
            maxEntryRelativeVolume = maxEntryRelativeVolume,
            maxEstimatedFeeR = maxEstimatedFeeR,
            targetR = targetR,
            exitMode = VolumeFlowExitMode.valueOf(exitMode),
            runnerTrailActivationR = runnerTrailActivationR,
            runnerTrailDistanceR = runnerTrailDistanceR,
            trendBreakLookbackM1Candles = trendBreakLookbackM1Candles,
            breakevenTriggerR = breakevenTriggerR,
            followThroughCheckM1Candles = followThroughCheckM1Candles,
            minFollowThroughR = minFollowThroughR,
            followThroughMinContextRangePct = followThroughMinContextRangePct,
            adverseExitCheckM1Candles = adverseExitCheckM1Candles,
            maxAdverseRBeforeExit = maxAdverseRBeforeExit,
            minFavorableRBeforeAdverseExit = minFavorableRBeforeAdverseExit,
            profitProtectActivationR = profitProtectActivationR,
            profitProtectFloorR = profitProtectFloorR,
            maxHoldM1Candles = maxHoldM1Candles,
            dailyTargetPct = dailyTargetPct,
            dailyStopPct = dailyStopPct,
            minTradesPerDay = minTradesPerDay,
            maxTradesPerDay = maxTradesPerDay,
            maxConsecutiveLosses = maxConsecutiveLosses,
        )
}

@Serializable
data class VolumeFlowBacktestResponse(
    val engineVersion: String,
    val fillModelVersion: String,
    val validationStatus: String,
    val symbol: String,
    val m1CandleCount: Int,
    val m5CandleCount: Int,
    val m15CandleCount: Int,
    val startAt: String?,
    val endAt: String?,
    val initialEquity: Double,
    val finalEquity: Double,
    val netPnl: Double,
    val netReturnPct: Double,
    val compoundDailyReturnPct: Double,
    val maxDrawdownPct: Double,
    val markToMarketMaxDrawdownPct: Double,
    val averageMaxFavorableExcursionR: Double,
    val averageMaxAdverseExcursionR: Double,
    val averageMfeCapturePct: Double?,
    val tradeCount: Int,
    val wins: Int,
    val losses: Int,
    val liquidationCount: Int,
    val winRatePct: Double,
    val profitFactor: Double?,
    val expectancyR: Double,
    val averageWinR: Double,
    val averageLossR: Double,
    val payoffRatio: Double?,
    val breakevenWinRatePct: Double?,
    val winRateEdgePct: Double?,
    val maxConsecutiveLosses: Int,
    val observedDays: Int,
    val activeDays: Int,
    val activeDayCoveragePct: Double,
    val averageTradesPerDay: Double,
    val averageTradesPerActiveDay: Double,
    val tradeFrequencyTargetDays: Int,
    val tradeFrequencyTargetPct: Double,
    val belowMinTradeDays: Int,
    val aboveMaxTradeDays: Int,
    val targetHitDays: Int,
    val stopHitDays: Int,
    val setupCount: Int,
    val rejectedSetupCount: Int,
    val noTradeReasonCounts: Map<String, Int>,
    val performanceBySetupMode: List<VolumeFlowTagSummaryResponse>,
    val performanceBySide: List<VolumeFlowTagSummaryResponse>,
    val performanceByExitReason: List<VolumeFlowTagSummaryResponse>,
    val performanceByMarketRegime: List<VolumeFlowTagSummaryResponse>,
    val performanceByVolumePattern: List<VolumeFlowTagSummaryResponse>,
    val trades: List<VolumeFlowTradeResponse>,
)

@Serializable
data class VolumeFlowTagSummaryResponse(
    val tag: String,
    val tradeCount: Int,
    val netPnl: Double,
    val winRatePct: Double,
    val profitFactor: Double?,
    val expectancyR: Double,
    val averageWinR: Double,
    val averageLossR: Double,
    val payoffRatio: Double?,
    val breakevenWinRatePct: Double?,
    val winRateEdgePct: Double?,
    val averageMaxFavorableExcursionR: Double,
    val averageMaxAdverseExcursionR: Double,
    val averageMfeCapturePct: Double?,
)

@Serializable
data class VolumeFlowTradeResponse(
    val side: String,
    val setupMode: String,
    val setupAt: String,
    val entryAt: String,
    val exitAt: String,
    val entryPrice: Double,
    val stopPrice: Double,
    val targetPrice: Double,
    val exitPrice: Double,
    val quantity: Double,
    val grossPnl: Double,
    val fees: Double,
    val pnl: Double,
    val returnR: Double,
    val riskMultiplier: Double,
    val macroTrendMovePct: Double?,
    val macroTrendEfficiency: Double?,
    val contextTrendMovePct: Double?,
    val contextTrendEfficiency: Double?,
    val contextRangePct: Double?,
    val contextQuoteVolume: Double?,
    val entryDelayM1Candles: Int,
    val entryBodyRatio: Double,
    val entryCloseLocation: Double,
    val entryRelativeVolume: Double?,
    val entryVolumeZScore: Double?,
    val entryRiskPct: Double,
    val maxFavorableExcursionR: Double,
    val maxAdverseExcursionR: Double,
    val mfeCapturePct: Double?,
    val maxFavorablePrice: Double,
    val maxAdversePrice: Double,
    val maxUnrealizedProfitPct: Double,
    val maxUnrealizedDrawdownPct: Double,
    val exitReason: String,
    val marketRegime: String,
    val keyLevelType: String,
    val keyLevelDistancePct: Double,
    val volumePattern: String,
    val relativeVolume: Double,
    val volumeZScore: Double,
    val setupBodyRatio: Double,
    val setupCloseLocation: Double,
)

private fun VolumeFlowBacktestReport.toResponse(): VolumeFlowBacktestResponse =
    VolumeFlowBacktestResponse(
        engineVersion = engineVersion,
        fillModelVersion = fillModelVersion,
        validationStatus = validationStatus.name,
        symbol = symbol.value,
        m1CandleCount = m1CandleCount,
        m5CandleCount = m5CandleCount,
        m15CandleCount = m15CandleCount,
        startAt = startAt?.toString(),
        endAt = endAt?.toString(),
        initialEquity = initialEquity.roundForApi(),
        finalEquity = finalEquity.roundForApi(),
        netPnl = netPnl.roundForApi(),
        netReturnPct = netReturnPct.roundForApi(),
        compoundDailyReturnPct = compoundDailyReturnPct(netReturnPct, observedDays).roundForApi(),
        maxDrawdownPct = maxDrawdownPct.roundForApi(),
        markToMarketMaxDrawdownPct = markToMarketMaxDrawdownPct.roundForApi(),
        averageMaxFavorableExcursionR = averageMaxFavorableExcursionR.roundForApi(),
        averageMaxAdverseExcursionR = averageMaxAdverseExcursionR.roundForApi(),
        averageMfeCapturePct = averageMfeCapturePct?.roundForApi(),
        tradeCount = tradeCount,
        wins = wins,
        losses = losses,
        liquidationCount = liquidationCount,
        winRatePct = winRatePct.roundForApi(),
        profitFactor = profitFactor?.roundForApi(),
        expectancyR = expectancyR.roundForApi(),
        averageWinR = averageWinR.roundForApi(),
        averageLossR = averageLossR.roundForApi(),
        payoffRatio = payoffRatio?.roundForApi(),
        breakevenWinRatePct = breakevenWinRatePct?.roundForApi(),
        winRateEdgePct = winRateEdgePct?.roundForApi(),
        maxConsecutiveLosses = maxConsecutiveLosses,
        observedDays = observedDays,
        activeDays = activeDays,
        activeDayCoveragePct = activeDayCoveragePct.roundForApi(),
        averageTradesPerDay = averageTradesPerDay.roundForApi(),
        averageTradesPerActiveDay = averageTradesPerActiveDay.roundForApi(),
        tradeFrequencyTargetDays = tradeFrequencyTargetDays,
        tradeFrequencyTargetPct = tradeFrequencyTargetPct.roundForApi(),
        belowMinTradeDays = belowMinTradeDays,
        aboveMaxTradeDays = aboveMaxTradeDays,
        targetHitDays = targetHitDays,
        stopHitDays = stopHitDays,
        setupCount = setupCount,
        rejectedSetupCount = rejectedSetupCount,
        noTradeReasonCounts = noTradeReasonCounts,
        performanceBySetupMode = performanceBySetupMode.map(VolumeFlowTagSummary::toResponse),
        performanceBySide = performanceBySide.map(VolumeFlowTagSummary::toResponse),
        performanceByExitReason = performanceByExitReason.map(VolumeFlowTagSummary::toResponse),
        performanceByMarketRegime = performanceByMarketRegime.map(VolumeFlowTagSummary::toResponse),
        performanceByVolumePattern = performanceByVolumePattern.map(VolumeFlowTagSummary::toResponse),
        trades = trades.takeLast(20).map(VolumeFlowBacktestTrade::toResponse),
    )

private fun VolumeFlowTagSummary.toResponse(): VolumeFlowTagSummaryResponse =
    VolumeFlowTagSummaryResponse(
        tag = tag,
        tradeCount = tradeCount,
        netPnl = netPnl.roundForApi(),
        winRatePct = winRatePct.roundForApi(),
        profitFactor = profitFactor?.roundForApi(),
        expectancyR = expectancyR.roundForApi(),
        averageWinR = averageWinR.roundForApi(),
        averageLossR = averageLossR.roundForApi(),
        payoffRatio = payoffRatio?.roundForApi(),
        breakevenWinRatePct = breakevenWinRatePct?.roundForApi(),
        winRateEdgePct = winRateEdgePct?.roundForApi(),
        averageMaxFavorableExcursionR = averageMaxFavorableExcursionR.roundForApi(),
        averageMaxAdverseExcursionR = averageMaxAdverseExcursionR.roundForApi(),
        averageMfeCapturePct = averageMfeCapturePct?.roundForApi(),
    )

private fun VolumeFlowBacktestTrade.toResponse(): VolumeFlowTradeResponse =
    VolumeFlowTradeResponse(
        side = side.name,
        setupMode = setupMode.name,
        setupAt = setupAt.toString(),
        entryAt = entryAt.toString(),
        exitAt = exitAt.toString(),
        entryPrice = entryPrice.roundForApi(),
        stopPrice = stopPrice.roundForApi(),
        targetPrice = targetPrice.roundForApi(),
        exitPrice = exitPrice.roundForApi(),
        quantity = quantity.roundForApi(),
        grossPnl = grossPnl.roundForApi(),
        fees = fees.roundForApi(),
        pnl = pnl.roundForApi(),
        returnR = returnR.roundForApi(),
        riskMultiplier = riskMultiplier.roundForApi(),
        macroTrendMovePct = macroTrendMovePct?.roundForApi(),
        macroTrendEfficiency = macroTrendEfficiency?.roundForApi(),
        contextTrendMovePct = contextTrendMovePct?.roundForApi(),
        contextTrendEfficiency = contextTrendEfficiency?.roundForApi(),
        contextRangePct = contextRangePct?.roundForApi(),
        contextQuoteVolume = contextQuoteVolume?.roundForApi(),
        entryDelayM1Candles = entryDelayM1Candles,
        entryBodyRatio = entryBodyRatio.roundForApi(),
        entryCloseLocation = entryCloseLocation.roundForApi(),
        entryRelativeVolume = entryRelativeVolume?.roundForApi(),
        entryVolumeZScore = entryVolumeZScore?.roundForApi(),
        entryRiskPct = entryRiskPct.roundForApi(),
        maxFavorableExcursionR = maxFavorableExcursionR.roundForApi(),
        maxAdverseExcursionR = maxAdverseExcursionR.roundForApi(),
        mfeCapturePct = mfeCapturePct?.roundForApi(),
        maxFavorablePrice = maxFavorablePrice.roundForApi(),
        maxAdversePrice = maxAdversePrice.roundForApi(),
        maxUnrealizedProfitPct = maxUnrealizedProfitPct.roundForApi(),
        maxUnrealizedDrawdownPct = maxUnrealizedDrawdownPct.roundForApi(),
        exitReason = exitReason.name,
        marketRegime = marketRegime.name,
        keyLevelType = keyLevelType.name,
        keyLevelDistancePct = keyLevelDistancePct.roundForApi(),
        volumePattern = volumePattern.name,
        relativeVolume = relativeVolume.roundForApi(),
        volumeZScore = volumeZScore.roundForApi(),
        setupBodyRatio = setupBodyRatio.roundForApi(),
        setupCloseLocation = setupCloseLocation.roundForApi(),
    )
